title: Sanyog Vyawahare # your name (or website title) here
logo: "/images/profile.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  AI Masters Student at Radboud University, Nijmegen 
  <br><br>
  “By far the greatest danger of Artificial Intelligence is that people conclude too early that they understand it.” 
  ― Eliezer Yudkowsky 
  <br><br>
  <a href="https://www.linkedin.com/in/sanyogv/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
