title: Sanyog Vyawahare
logo: "/images/profile.jpeg?raw=true"
description: > 
  AI Masters Student at Radboud University, Nijmegen 
  <br><br>
  “By far the greatest danger of Artificial Intelligence is that people conclude too early that they understand it.” 
  ― Eliezer Yudkowsky 
  <br><br>
  <a href="https://www.linkedin.com/in/sanyogv/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-190418770-1
